# Generated by Django 5.2.18 on 2026-10-08 18:08

import django.db.models.deletion
import uuid
import webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('event_types', models.JSONField(blank=True, default=list, help_text='Empty means every event type.')),
                ('secret', models.CharField(default=webhooks.models.new_signing_secret, max_length=64)),
                ('previous_secret', models.CharField(blank=True, max_length=64)),
                ('previous_secret_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('disabled_reason', models.CharField(blank=True, max_length=200)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('failing_since', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_second', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('succeeded', 'Succeeded'), ('dead', 'Dead')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Attempts in the current retry cycle.')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.endpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.event')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('succeeded', models.BooleanField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('response_excerpt', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='webhooks.delivery')),
            ],
            options={
                'ordering': ['number'],
                'indexes': [models.Index(fields=['-created_at'], name='webhooks_de_created_b83e45_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['tenant', 'status'], name='webhooks_en_tenant__b08bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', '-created_at'], name='webhooks_ev_tenant__e5ec96_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='uniq_event_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='webhooks_de_status_c8abe7_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['endpoint', '-created_at'], name='webhooks_de_endpoin_a9f10e_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('event', 'endpoint'), name='uniq_delivery_event_endpoint'),
        ),
    ]
